--- #YAML:1.0
name:               Rubyish-Attribute
version:            0.05
abstract:           ruby-like accessor builder: attr_accessor, attr_writer and attr_reader.
author:
    - shelling, <navyblueshellingford@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Sub::Exporter:  0
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
