--- #YAML:1.0
name:               Rubyish-Attribute
version:            1.2
abstract:           ruby-like accessor builder: attr_accessor, attr_writer and attr_reader.
author:
    - shelling, <navyblueshellingford@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PadWalker:  0
    perl:       5.010
    Want:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
